//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Ailand.ConsoleApp.AilandAPI {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PerformWinServiceSoap", Namespace="http://tempuri.org/")]
    public partial class PerformWinService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback StartServiceEventOperationCompleted;
        
        private System.Threading.SendOrPostCallback TryServiceEventOperationCompleted;
        
        private System.Threading.SendOrPostCallback EndServiceEventOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PerformWinService() {
            this.Url = global::Ailand.ConsoleApp.Properties.Settings.Default.Ailand_ConsoleApp_AilandAPI_PerformWinService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event StartServiceEventCompletedEventHandler StartServiceEventCompleted;
        
        /// <remarks/>
        public event TryServiceEventCompletedEventHandler TryServiceEventCompleted;
        
        /// <remarks/>
        public event EndServiceEventCompletedEventHandler EndServiceEventCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StartServiceEvent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable StartServiceEvent() {
            object[] results = this.Invoke("StartServiceEvent", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void StartServiceEventAsync() {
            this.StartServiceEventAsync(null);
        }
        
        /// <remarks/>
        public void StartServiceEventAsync(object userState) {
            if ((this.StartServiceEventOperationCompleted == null)) {
                this.StartServiceEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartServiceEventOperationCompleted);
            }
            this.InvokeAsync("StartServiceEvent", new object[0], this.StartServiceEventOperationCompleted, userState);
        }
        
        private void OnStartServiceEventOperationCompleted(object arg) {
            if ((this.StartServiceEventCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StartServiceEventCompleted(this, new StartServiceEventCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TryServiceEvent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TryServiceEvent(string[] resultArr) {
            this.Invoke("TryServiceEvent", new object[] {
                        resultArr});
        }
        
        /// <remarks/>
        public void TryServiceEventAsync(string[] resultArr) {
            this.TryServiceEventAsync(resultArr, null);
        }
        
        /// <remarks/>
        public void TryServiceEventAsync(string[] resultArr, object userState) {
            if ((this.TryServiceEventOperationCompleted == null)) {
                this.TryServiceEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTryServiceEventOperationCompleted);
            }
            this.InvokeAsync("TryServiceEvent", new object[] {
                        resultArr}, this.TryServiceEventOperationCompleted, userState);
        }
        
        private void OnTryServiceEventOperationCompleted(object arg) {
            if ((this.TryServiceEventCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TryServiceEventCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EndServiceEvent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EndServiceEvent(string message) {
            this.Invoke("EndServiceEvent", new object[] {
                        message});
        }
        
        /// <remarks/>
        public void EndServiceEventAsync(string message) {
            this.EndServiceEventAsync(message, null);
        }
        
        /// <remarks/>
        public void EndServiceEventAsync(string message, object userState) {
            if ((this.EndServiceEventOperationCompleted == null)) {
                this.EndServiceEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEndServiceEventOperationCompleted);
            }
            this.InvokeAsync("EndServiceEvent", new object[] {
                        message}, this.EndServiceEventOperationCompleted, userState);
        }
        
        private void OnEndServiceEventOperationCompleted(object arg) {
            if ((this.EndServiceEventCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EndServiceEventCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void StartServiceEventCompletedEventHandler(object sender, StartServiceEventCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StartServiceEventCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StartServiceEventCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TryServiceEventCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void EndServiceEventCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591